2025-02-14T19:55:48-08:00
Repo:
- https://github.com/ChartMimic/ChartMimic
Checking it out because of this paper:
- Transforming Science with Large Language Models: A Survey on AI-assisted Scientific Discovery, Experimentation, Content Generation, and Evaluation
- https://arxiv.org/abs/2502.05151


Cloned the repo.
Got a deepseek API.
- nah cannot top up

2025-02-14T20:03:34-08:00

Going to use the opanAI pro account I got for free.
- tested API working

Following ChartMimic repo:
```
cd ChartMimic # cd to the root directory of this repository
mkdir dataset
wget https://huggingface.co/datasets/ChartMimic/ChartMimic/resolve/main/test.tar.gz
tar -xzvf test.tar.gz -C dataset
```

2025-02-14T20:23:40-08:00
Next:
```
export PROJECT_PATH=${YOUR_PROJECT_PATH}

# Step 1: Get Model Reponse
bash scripts/direct_mimic/run_generation.sh

# Step 2: Run the Code in the Response
bash scripts/direct_mimic/run_code.sh

# Step 3: Get Lowlevel Score
bash scripts/direct_mimic/run_evaluation_lowlevel.sh

# Step 4: Get Highlevel Score
bash scripts/direct_mimic/run_evaluation_highlevel.sh
```


Fuck bash script, fuck python version.
I'm directly running it:
```
python3 chart2code/main.py \

--cfg_path eval_configs/direct_generation.yaml \

--tasks chart2code \

--model gpt-4-vision-preview
```

Fixing missing modules, the slightly non-trivial ones:
- `pip install google-generativeai`
![[Pasted image 20250214203106.png]]
Why tf do I need deepseek, they don't even let me top up their api...
- `pip install deepseek-vl`
- Still fucking complaining.
- Going to fix the code.

2025-02-14T20:50:14-08:00
Commented out the lines about deepseek.
![[Pasted image 20250214205703.png]]

`pip install PyPDF2`
`pip install pdf2image`

Set project path in python:
```
import os

  

os.environ["PROJECT_PATH"] = "/Users/wentaojiang/Documents/GitHub/ChartMimic"

  

print(os.environ["PROJECT_PATH"]) # Verify it's set

  

from dotenv import load_dotenv

  

load_dotenv() # Load environment variables

  

print(os.environ.get("PROJECT_PATH")) # Debugging: Check if it's loaded correctly
```


`pip install colormath`

2025-02-14T22:18:56-08:00

Error about json...

Hmm `run_task` is running something, but I'm only getting the:
![[Pasted image 20250214222559.png]]

2025-02-14T22:28:45-08:00
Shit is running??
![[Pasted image 20250214222849.png]]
- I updated the bash script to use `python3` instead of `python`
- And updated the `.env` in both repo root folder and the `chart2code`
Getting error:
- Error code: 404 - {'error': {'message': 'The model `gpt-4-vision-preview` has been deprecated, learn more here: https://platform.openai.com/docs/deprecations', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}

Change the bash to:
```
model=gpt-4-turbo

  

python3 chart2code/main.py \

--cfg_path eval_configs/direct_generation.yaml \

--tasks chart2code \

--model ${model}
```

New error:
![[Pasted image 20250214223247.png]]

Add the following to the config `direct_generation.yaml`:
```
llm:
  gpt-4-turbo:
      name: gpt
      engine: gpt-4-turbo
      context_length: 4096
      max_tokens: 4096
      temperature: 0.0
      top_p: 1
      retry_delays: 20
      max_retry_iters: 15
      stop: []

```
Error:
- Error code: 404 - {'error': {'message': 'The model `gpt-4-turbo` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}

Available models:
- ['gpt-4o-mini-audio-preview-2024-12-17', 'dall-e-3', 'dall-e-2', 'gpt-4o-audio-preview-2024-10-01', 'gpt-4o-audio-preview', 'o1-mini-2024-09-12', 'o1-preview-2024-09-12', 'o1-mini', 'o1-preview', 'whisper-1', 'gpt-4o-mini-audio-preview', 'babbage-002', 'tts-1-hd-1106', 'tts-1-hd', 'text-embedding-3-large', 'tts-1', 'tts-1-1106', 'davinci-002', 'gpt-3.5-turbo-1106', 'gpt-4o-2024-08-06', 'gpt-4o-mini-2024-07-18', 'gpt-4o-mini', 'gpt-4o', 'omni-moderation-2024-09-26', 'gpt-3.5-turbo-instruct', 'gpt-3.5-turbo-instruct-0914', 'gpt-3.5-turbo-0125', 'gpt-3.5-turbo', 'gpt-3.5-turbo-16k', 'text-embedding-3-small', 'text-embedding-ada-002', 'gpt-4o-2024-05-13', 'omni-moderation-latest', 'gpt-4o-2024-11-20']
- got from running
```
import openai

models = openai.Client().models.list()
print([model.id for model in models.data])

```

![[Pasted image 20250214224306.png]]
Fuck. Why?? There's clearly no usage:
![[Pasted image 20250214232023.png]]


